apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"opentelemetry-operator","control-plane":"controller-manager"},"name":"opentelemetry-operator-system"}}
  creationTimestamp: "2025-12-27T14:07:19Z"
  labels:
    app.kubernetes.io/name: opentelemetry-operator
    control-plane: controller-manager
    kubernetes.io/metadata.name: opentelemetry-operator-system
  name: opentelemetry-operator-system
  resourceVersion: "805612"
  uid: 3ae6ca0b-c3b1-4030-b8d4-9aa511a4dc3e
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
