apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"pod-security.kubernetes.io/audit":"privileged","pod-security.kubernetes.io/enforce":"privileged","pod-security.kubernetes.io/warn":"privileged"},"name":"parca"}}
  creationTimestamp: "2025-12-29T13:47:17Z"
  labels:
    kubernetes.io/metadata.name: parca
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: parca
  resourceVersion: "1826783"
  uid: 7ca2f430-6f2e-42da-8202-ad5101f4e557
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
