apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: obs
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-12-27T11:41:34Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/instance: obs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.3.0
    helm.sh/chart: grafana-10.4.0
  name: obs-grafana
  namespace: monitoring
  resourceVersion: "1842166"
  uid: c95164c7-25b2-4543-bfcb-8ba63d6f3627
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.103.194
  clusterIPs:
  - 10.0.103.194
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-web
    nodePort: 30267
    port: 80
    protocol: TCP
    targetPort: grafana
  selector:
    app.kubernetes.io/instance: obs
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 4.157.92.17
      ipMode: VIP
