apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-aiops-genai-jira
  namespace: spring-petclinic
  labels:
    app: petclinic-aiops-genai-jira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-aiops-genai-jira
  template:
    metadata:
      labels:
        app: petclinic-aiops-genai-jira
    spec:
      containers:
        - name: petclinic-aiops-genai-jira
          image: k8snewacr.azurecr.io/petclinic-aiops-genai-jira:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
