apiVersion: v1
kind: Service
metadata:
  name: petclinic-aiops-genai-jira
  namespace: spring-petclinic
spec:
  selector:
    app: petclinic-aiops-genai-jira
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
