apiVersion: v1
data:
  ip-masq-agent-reconciled: |
    MasqLinkLocal: true
    NonMasqueradeCIDRs:
    - 10.244.0.0/16
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-25T19:03:57Z"
  labels:
    app.kubernetes.io/managed-by: Eno
    component: ip-masq-agent
  name: azure-ip-masq-agent-config-reconciled
  namespace: kube-system
  resourceVersion: "250"
  uid: 63241272-7701-4a53-8226-77593b2d8bc1
