apiVersion: v1
data:
  cns_config.json: |-
    {
      "CNIConflistFilepath": "/etc/cni/net.d/15-azure-swift-overlay.conflist",
      "CNIConflistScenario": "v4overlay",
      "ChannelMode": "CRD",
      "EnableAsyncPodDelete": true,
      "EnableCNIConflistGeneration": true,
      "EnableIPAMv2": false,
      "EnableK8sDevicePlugin": false,
      "EnableLoggerV2": false,
      "EnableStateMigration": false,
      "EnableSubnetScarcity": false,
      "InitializeFromCNI": true,
      "ManageEndpointState": false,
      "ManagedSettings": {
        "InfrastructureNetworkID": "",
        "NodeID": "",
        "NodeSyncIntervalInSeconds": 30,
        "PrivateEndpoint": ""
      },
      "MetricsBindAddress": ":10092",
      "ProgramSNATIPTables": false,
      "TelemetrySettings": {
        "DebugMode": false,
        "DisableAll": false,
        "HeartBeatIntervalInMins": 30,
        "RefreshIntervalInSecs": 15,
        "SnapshotIntervalInMins": 60,
        "TelemetryBatchIntervalInSecs": 15,
        "TelemetryBatchSizeBytes": 16384
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-25T19:03:57Z"
  name: cns-config
  namespace: kube-system
  resourceVersion: "260"
  uid: 1afe4619-ba22-40d3-916e-df3827556d09
