apiVersion: v1
data:
  cns_config.json: |-
    {
      "CNIConflistFilepath": "C:\\k\\azurecni\\netconf\\10-azure.conflist",
      "CNIConflistScenario": "v4overlay",
      "ChannelMode": "CRD",
      "EnableAsyncPodDelete": true,
      "EnableCNIConflistGeneration": false,
      "EnableIPAMv2": false,
      "EnableK8sDevicePlugin": false,
      "EnableLoggerV2": false,
      "EnableStateMigration": false,
      "EnableSubnetScarcity": false,
      "InitializeFromCNI": false,
      "ManageEndpointState": true,
      "ManagedSettings": {
        "InfrastructureNetworkID": "",
        "NodeID": "",
        "NodeSyncIntervalInSeconds": 30,
        "PrivateEndpoint": ""
      },
      "MetricsBindAddress": ":10092",
      "ProgramSNATIPTables": false,
      "TelemetrySettings": {
        "DebugMode": false,
        "DisableAll": false,
        "HeartBeatIntervalInMins": 30,
        "RefreshIntervalInSecs": 15,
        "SnapshotIntervalInMins": 60,
        "TelemetryBatchIntervalInSecs": 15,
        "TelemetryBatchSizeBytes": 16384
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-25T19:03:57Z"
  name: cns-win-config
  namespace: kube-system
  resourceVersion: "239"
  uid: b8c8c86f-a11d-468b-aa1f-43edcba1f992
