apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: obs
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-12-27T11:11:50Z"
  labels:
    app: kube-prometheus-stack-kube-etcd
    app.kubernetes.io/instance: obs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 80.7.0
    chart: kube-prometheus-stack-80.7.0
    heritage: Helm
    jobLabel: kube-etcd
    release: obs
  name: obs-kube-prometheus-stack-kube-etcd
  namespace: kube-system
  resourceVersion: "741201"
  uid: 90d44626-3c48-4797-bb23-c3ae8fe05891
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 2381
    protocol: TCP
    targetPort: 2381
  selector:
    component: etcd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
