apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2025-12-27T11:11:55Z"
  labels:
    app.kubernetes.io/managed-by: prometheus-operator
    managed-by: prometheus-operator
  name: alertmanager-obs-kube-prometheus-stack-alertmanager-tls-assets-0
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Alertmanager
    name: obs-kube-prometheus-stack-alertmanager
    uid: 0e1260a3-3273-443d-a3e8-77cae10d14c9
  resourceVersion: "741415"
  uid: e38b9ad5-4d63-429b-9302-66284bbdd653
type: Opaque
