apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: obs
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-12-27T11:11:50Z"
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/component: prometheus-operator
    app.kubernetes.io/instance: obs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 80.7.0
    chart: kube-prometheus-stack-80.7.0
    heritage: Helm
    release: obs
  name: obs-kube-prometheus-stack-operator
  namespace: monitoring
  resourceVersion: "741242"
  uid: edf069c6-225c-4262-b036-26d39ad506e9
spec:
  clusterIP: 10.0.56.160
  clusterIPs:
  - 10.0.56.160
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: kube-prometheus-stack-operator
    release: obs
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
