apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: obs
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-12-27T11:11:50Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: obs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 80.7.0
    chart: kube-prometheus-stack-80.7.0
    heritage: Helm
    release: obs
    self-monitor: "true"
  name: obs-kube-prometheus-stack-prometheus
  namespace: monitoring
  resourceVersion: "744749"
  uid: d4246a1f-8156-4ca9-9162-63da90f93bac
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.146.4
  clusterIPs:
  - 10.0.146.4
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-web
    nodePort: 32575
    port: 9090
    protocol: TCP
    targetPort: 9090
  - appProtocol: http
    name: reloader-web
    nodePort: 32168
    port: 8080
    protocol: TCP
    targetPort: reloader-web
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: obs-kube-prometheus-stack-prometheus
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 4.255.55.128
      ipMode: VIP
