apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: obs
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-12-27T11:11:50Z"
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: obs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 80.7.0
    chart: kube-prometheus-stack-80.7.0
    heritage: Helm
    release: obs
    self-monitor: "true"
  name: obs-kube-prometheus-stack-alertmanager
  namespace: monitoring
  resourceVersion: "741238"
  uid: 8b85a236-6e18-4551-b23a-aa90530635b8
spec:
  clusterIP: 10.0.174.199
  clusterIPs:
  - 10.0.174.199
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-web
    port: 9093
    protocol: TCP
    targetPort: 9093
  - appProtocol: http
    name: reloader-web
    port: 8080
    protocol: TCP
    targetPort: reloader-web
  selector:
    alertmanager: obs-kube-prometheus-stack-alertmanager
    app.kubernetes.io/name: alertmanager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
