apiVersion: v1
data:
  web-config.yaml: ""
kind: Secret
metadata:
  creationTimestamp: "2025-12-27T11:11:55Z"
  labels:
    app.kubernetes.io/managed-by: prometheus-operator
    managed-by: prometheus-operator
  name: prometheus-obs-kube-prometheus-stack-prometheus-web-config
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Prometheus
    name: obs-kube-prometheus-stack-prometheus
    uid: 3552afec-6ab4-45c6-9fe0-acf52932b48e
  resourceVersion: "741451"
  uid: 85dbb9b2-ce12-44fb-b7f7-87ac2627ea9d
type: Opaque
