apiVersion: v1
data:
  prometheus.http-client-file.yaml: dGxzX2NvbmZpZzoKICBpbnNlY3VyZV9za2lwX3ZlcmlmeTogdHJ1ZQo=
kind: Secret
metadata:
  creationTimestamp: "2025-12-27T11:11:55Z"
  labels:
    app.kubernetes.io/managed-by: prometheus-operator
    managed-by: prometheus-operator
  name: prometheus-obs-kube-prometheus-stack-prometheus-thanos-prometheus-http-client-file
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Prometheus
    name: obs-kube-prometheus-stack-prometheus
    uid: 3552afec-6ab4-45c6-9fe0-acf52932b48e
  resourceVersion: "741452"
  uid: bdcdcee3-2892-4003-a111-4b619e4ef125
type: Opaque
