apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: petclinic
  namespace: flux-system
spec:
  interval: 1h
  path: ./clusters/aks/petclinic
  prune: true
  sourceRef:
    kind: GitRepository
    name: petclinic
