apiVersion: v1
items:
- apiVersion: v1
  binaryData:
    crd.yaml: SDRzSUFBQUFBQUFBLyt3ODdXNGpONUwvL1JRRjN3SzJMNWFVM0M0T09kOWlBNi9IQ1FhVG1Samp5U3h3azl5Q1lwZlVYTFBKRHNtV3JWenUzUStzSWxzdHFic2x6eVNMUFdEN2w3dEZGb3RWeGZxbVJhM2VvL1BLbWlzUXRjS25nQ2ErK2VuRGwzNnE3R3oxeGNtRE1zVVYzRFErMk9vdGV0czRpUzl3b1l3S3lwcVRDb01vUkJCWEp3RENHQnRFL096aks0QzBKamlyTmJySkVzMzBvWm5qdkZHNlFFZkE4OUtyejZkL21INXhBaUFkMHZSM3FrSWZSRlZmZ1dtMFBnRXdvc0lyV0ttZkZUby9yWittQmE1T2ZJMHlMclIwdHFtdklIM2x3UWtEeHY0OXphTVBXdm53cXZQeFcrVUQvVkRyeGduZHJrSGZ2RExMUmd1WHY1NEFlR2xydklJM2NZbGFTQ3hPQU5KR2FNbEpSdlVMb2V0U2ZNRndaSW1WWUl3QWJJM20rdTdsKzkvZmIzMEdLTkJMcCtwQVJHSDBRSGtJSlFJUGhZVjE5SnFRaE91N2wrM3MydGthWFZCNTYveDBXTno1dXJQV1dVU0hSMEVSZVl1OGF0b1lGbWtIWUJjUVN1WEJZZTNRbzJGdWJ3R0dPRWdZc1BPL29ReFR1RWNYd1lBdmJhT0xLQklyZEFFY1NyczA2dWNXdG9kZ2FWRXRBaWFlYkI1bEFqb2pOS3lFYnZBU2hDbWdFbXR3R0ZlQnhuVGcwUkEvaGRmV0lTaXpzRmRRaGxEN3E5bHNxVUlXYldtcnFqRXFyR2NrcFdyZUJPdjhyTUFWNnBsWHk0bHdzbFFCWldnY3prU3RKb1M2SWZHZVZzVy91SFFZL05rV3JtRWQ1Y01IcDh5eTh3TUo0Z2dIb2t4R1pvczBsWGV4SVhUOEZLbno5dmIrSGVTbGlSbTcxQ2U2YnliNkRRc2l3WlJab0dNbUxweXRDQ2Fhb3JiS0JIcVJXcUhaSmI5djVwVUtrZTgvTmVoRDVOVVVidWk4d3h5aHFRc1JzSmpDU3dNM29rSjlJenorNWd5SWxQYVRTTmpqV05CVlZidURtV3FkSDdKdUdlQVhuODc3R3VYV2dTblFLeGRGT29pQThTQjBORTkrK3M5cGZFUVRiSzIwRGJzLzdDeCtuY2ZsUXpWSDhCaEFMY0ExeGtSUnVWTlBDc0VhK09iVjdXYjhkQTh1NzM1dXJVYXhlNDZsdHZMaGhzOHJ1Z000M1d3Tkp2S3BoVUlQajZXU0pUamJCR1V3bnZIR0krbXhwQW0yZWRUaWxTMEFxUVVCZm0wa0Z1QndnUTVObEh4VjRmNTIwRFRWUHFLVHlDUFI2RjJwanI4c1hTMEhxTEluUUlrb1RYRmRGRWZRZzhkbERTNkt3cUgzckVLUjRZQXlQZ2phVGlubytQV1FJaG1DRGF2cHJKSStzRU1NSFVDOThRRmRORjBIa1c5SHNrNktOcTAxUHRreUpkd3ZvZkdOMEhyZGd6dUx3VG9peTNLUWNOaUM0NkhBV3RzMUZxUldYaTRncXBVc1FjVmxEMXdCVHBqQ1ZvellvOUk2RW1hSkJoMHBvbWVSaFZ5YkY0VENLMXpmbzNSNDZBVGU5TTNKbkNhY0VwczkvL0pZb3V2akxldU1DQVVlY0IwQitHRGRNemNRZGRxMWxPajNGTW9PMWkvYWdWdEtTMGVOR3hHT2dGZ1NvNldZSXdnYTdNbkoyWDBlU3pTQVR5Z2Jra1VCdkZEVU9TemZ4T2pFVG9NZGZvTHd2cWx3MTNERlo5Rm96V2p3MHNlZjhLL1pUOXo5L0JZanlXVG8yY0lCaXQ1RXYxVUc2KzZFRTlVeHBOMlowZEdCTEFraDByam0zNUlDWEtobDA3TStaTkhvUWsya3pCQ0UyNkpwMG5EOHZmRjlJalJzZUtBOUJuZTNyNy9XWXRrN0FxSU9JNjlmNkx0UldBZkkyME8vZDlFaGlYNkFVTVluWEdBUk1XR0I3R2cvTVNDUXRDaTdrSGUzcjJHbEJLQlpLV2ROaFNiQVNqZ2w1aHA3WkFxRzNZQVdXUkdFRHc1RjllZG1zVUIzcjM3dVVhSjcyM3JSTXkyckNSTHpPWDBHSDcvWE80N0M1cEhXR0pRUjVCUmVNS041aXZMd0JieWVyd05PNFd2cm9GVExjaEpLWjV0bFdUY0JSRjFySlRrazY5T2p0SE1YdmNJWWVubDJNcFVIMDFUenFKb1hnRTgxT29WR3h0OElaVzM3em1WOEZ0WlZJbHhGWi8zMy96WkM1ZWpNTDNzM3UwZm1XajNneDlJNno4MEVyOFNUcXBvS0FsYTFkY0wxR1N5Z3FPOW4wdCtDOThzd002Zm11SWhlYmUxczFFL0tMSDhiVW95SVk1R3R6aUdWbE1lMUFyY3hOTUo3SzFVMGxmQ29RdGt4eHoyNFprTS81Vk9xUE9tWGVOYTBNZzlkVTg2dUdpc2xHVWU1bVhXOUZNcVFZa0JCSG5OamRMUkxIWWRCOUZ2WjU1bEdYSkVqMW9ickIyaDI5bUozUXRmRnp0b1dyTkZyVXVFRnJ0cm92MmVYZHBFY2NmYjIyQVVxeFFxakhsZG1TUTVoc0ZDaXJzRmhvVndNM1lJVGkwaS9ZQWZNZ3JTT0JucDBLOFY4UWRqSHZPT084SWVvU1FlZGtOVVdxcEUxS1pTdzVwTDJpaytpcWpWZXdXbXQ1YVRBMWVuMDdGbThVRDdxM3hpTWZFL3g0aUg1M1IyL0ZWUmdLTkZSeEpTaXo4U29udjNOWTRRYlFSVkRMdXp6NGlLTm9rRG5TMVhmYXRiS1I3a0kzdzVNNjJ3cmV3UVIyWlRHNkhPUzBpWmVmZWs3dUhqQUJEYkhYR21UamNjWStodXhqS0ZEMFpueVhCY2hMM0NIVHRuaTlZRHAzOXIwN2M2VTF2RXM3U01zS0oxZ2dsNW5YRVdJeWpuMDdScll2THZHZ09oc3ZVWHFFcFNCU21tdFBFcHJDcy9Ib3FhRlFXamZkNW9ZMzRDdWFwSFMxaXd6T285Q0JmYlZ4TzV5NE5EWDF2ZytyejQrY3lFZk5obVdpTy8xM1V0eTRUcnY1UEJyKzBnYkkzakZaUlFDcjRwQlg2RGZWQiswUXYvK2gxL1hDdFVpeUxKUFRJNzFFVWY5d3kwWnV1T2xXdEZKUys4Nmh1VHJzRjBhTkdWdHpvNkZJNXJDRktnUjBBNjAzVUF1eit6Vm40SmlQOGFyWU5DY3Z0c0NudlF4dlZ3Q0dta0xMRUQwQ1h1YkJlU1R2TENhcEtSRU9QVWhocmhMSmFGQ3QwemdUc0UxR2xsVVgzM1o0NTZOY1JLcjExaFp0LzVXVmVwUTRIdTNOWmlUQXhWOUFFMWZNaGV5RnpDUUdBaVduUFRhRm9QSTlvcEdpK3hiemtRZWkyNGF2b1Z3U21aK0RNcndNbkRXSVJxZ1NnU2VSS210MEdYK05tMzdmS3VkWk1memlHR0xRL3UzeFZhb1gxdXRKTHN1WEd2WjZMcCtWb3diaEwyQ3o5NkEzeXhndk40c3ZSTm9kNUFpaHpRRUljdCtaeW9Sa2VkRi9FVElsUG5JT0ZHTE9lcS9PekcrcFZWMzZNQ29iSkdnM2V6QXFyOEtDWXd0OEI0NVovSDNKc1RabTg3aXFaeVMzMWlWVm8ybmtrVndEV1UwaDVZdDJWa0tGaGFLa2xxQ05qYUYreDU0RmVsM0huRjJOdVM5Sklaazl5MkJqNEZGTkJ1TnBzQ0NyUWt2dGFtZkRFRE1WWldIWm83T1lPU1lzclBDU2orVDFraXNBLzNCUG1XazBFeDRyNVptVXR0aUV0ZVlEUUNtOEd5aFVCY2dkNnM4WURsaDNlYjRJcDFaWUlxZWlBQU9TMHhybFk5d0tITUoybWR6MnRiQ1VpaFpvV2w5dHBSUUduS1BQbUdmdmZER2xTVlFDbDZvdmtDaGQ2dW5OelNhU3RhZFVDN2FsWlppbDBtOUR5WEVnRHhHMGd6VFBJbkJYcktrNVhRaHpOZnNUeDZrV1h4K01HMEVMd3hRcFR1UlVaZ2ljOEp6MkpVcmx5L1dSbFJLWmdaZWEyMWxYL200K3l4UWhNWWhMRVhBYWJzcXJ4U1hyNm9teEdCcGVqb0lSQVVjby9pQWVCR05OdVVtRDliRUtKSnpaZEdzM2tlS2JvMGUwSmI4SEJZTmZreHZjV1lFWWFyUmRKUlExMi90NG53QUp0bkJhWStZWkJjMmVoSlV4VWkxNDhpQ2d6QlRxb2pjcFVvOFpKKzlQYkppSlpTbVlGZFJ6QVBpSU1panhCT09NUno4NUFUVUdORzVwMk5rd0FIOTFoMGtuQk5EaVVlQXA4bEdsVS9pdVo5VW9wNDg0SHBFYkE1Z3R3K1NFYWxFUFdTbm9xODZzdUJ6ekRlTk4rdnZGdVAwUFpRWDNoMTVrSzIxQ0FHZHVZTC9Qdi9oczE4bUYxK2RuMy80ZlBJZlAzNTIvc09VL3ZqWGk2OHVmc2t2bjExY25KOS9lUFg2bTNkM3R6K3FpMTgrbUtaNjRMZGZ6ai9nN1k5SEFybTQrT3AzSTBodHNVS1pNTEZ1d2p1NUluL2tPTE53UnJHRVR4L251SjNjRnBWdERGV2FwSzNxSm95SmJXdEZRTVQ0TWg3VW5wYU40NTBMVGpKTldyQ1Q5ckQ2V2I5akFNY2RudHgyOGsrWi9FZVZ5YmU1TVdoSEtwWDVCS25NdXBuU1p1MEt5b090VkFncG5kdng4b1lxWEVCdXdLWkVHaXlrTTZRV2JmWUduMnF0cEFwNjNTMnIybENpZTFTRGFUN2d4SUF3b0twYWsvTkpaMkdTM0RKT0JmeGpucXNEQXp6S3hxbXd2ckVtNEZOUHBnWDJpN2k0T3l0RlNkdDlTdGFBc1daU083VlNHcGVEeml1bldxNjE1cmcxZFJLeFVNQm1OdFRvS3VVOXA3NlYxdUNENnVrRzRDZlBGMTBJTzFoL3JIdWZ5Z3hIK3ZkL3lVV01QYUx0a1dzNFpFOTBvdFk3S1R6WFJod1ZtTzd1NzdnZG9KTVo3WVF6WTZjbEpPYytSa1FHSlhvdjNIclk0eHFybHVSbjRiK2hOdDNqYUhQTmgxQm84RTJkRDVibVR0OFV1TkNtL0hCaUp6NUM2NDE2OE5GMUYwU3R3U21ITStad1JCazdQcTR4MTgvYWNqdzkzN3g4a1lzYzNKZ1ozSnBiTTNQYldON01lS3pSM3p2ekcyM3llOS9YSFRpNHgrLy9YKzN4Z0pJTVZxTWJ5NEJ1bThsM20rSHNjL21jL0lsUk1tazVVbzVGUE1jcWxBT0lVNmhIY2JWUTFPSDdUUE95V1hPQ0swWDFyQm1CbWdoVFREWjdtZzJ4OVZmT0Q0M0c2SHNDUkltemlNQ0dtcFNJb0N4blVuUDhTMi81bEI5aDFreTkzUENXYTBvSXdhbGFJL3p4QWRlWDNHNk9pd1hLOENkby9KaUh4MjU0NGt5YlN2MWovdXRQUThKNlRHNkFNVGc2alhGTHcwR1pRc2xJQnQ0WGJaY2hSU0lScnVOaDlHMVZoelZVS0l6UFNVNnR0d0Q1YWJSalpxdTlqNE9KVWNCYzNDYnI5TWJlcC96bkpkeFJ4bVh6aGRKSmIrd3R0Um4ybE9rM3oxRSsrRU5mMDh3QUNUdU5NN3pmQjF5M2JicWRjNThOMGVoMmc1Mk8wakpHK0cxeE9IV0NZaHcvWnFRNytmcWMxYjU5VWo3NC84eVp2R3F1RENQSnkyYW1qd0tOV0dYMm1JSmVDYjFQSlg1RzltZ09mSmQzdDduTEFDTGljaFpEQTgxcXRGVDF1QXNBbTRyY0ZONExyWW9XRTVZL3BobnQ5ZmFuUnVpMnhlNFFTL1B3QkNDeTdLZEdyWVJHUStmclVlbENDc2RoQ2l1U1VZamVKcytHTkp3VXBsVmpHMG54M0poV0N4ZVViTFFZczVFQThld3Y3WmpuZGlUdk51Sit6ODBWUnpQeDNlN01MamZEcGtIRExzYXByU3JjUFhqbjJ4VWR1OGk2clZVWUIwNVBqdTA2S1UzS0tpK05kVmhjYkt6SVJndU1xOHMvcjNPUWVRbGNIYWZpTG9iTFhDMUt4ekN4dFFVN0NuVmhIYTdRd1hsaENSNlo3SXNwL0JjNlMySnJjQ21DV3VXV0lZcUJSaUZTL1lzTU1nZ1BuOE01Z1FSVlZWZ29FVkN2TDdnZWdPRFhQbUExdHUzalBLM2ovTWxrR0k2V3J2ZFVhTjlTMDF4NzN4R1ZaTjRQNnVpa2dWdTlxbnc2M1plZHV2NG1PanRHUmJkQzlyY29wd0ljMHBYQ2RPSSs4V1FlR2VQM0o1MUhKanRjS2gvY29SYlRzN2RwM0U3cFdWVmlpUzJRZk9uSGlVaUxQaWU2RklhN0Q4L09mRDVCbStublMrbW15bDVNNFM5SS9jZ3lrUHUyc080eHFsZXZoZTlucnVxQVpaeHFFVXBXK3c1ckxXUnVnQlZ3T2pubEh1cE5ueU92TzZzamlJbjFQdjFWNEdyR0Z6Qm4rVXJaWHoxZHNmc3JMWExGTnhqN1NsS2ROdmJHSjEvMTlIZDVwek5lY05JdU9Ha1huUENDazlFRm45ZVAyWGk4RGJMNGJ0QXNiN0g2KyszUlBiMlk1UDRtOUhKcjZqQUpva0Jna0d3Y2ZiQk9MSi9aaHJucXU5YTZoM2UrMXFxMkwraWx5VG5rUExJZnRJZU9ROWNIZ3dpTlAzeUJrSVp0dGVqWU9iSDJZKzhReWhMbGcrKzdJN09UWDhrRE13bTA4SHdyMTBpbHNXaXZuZFVvazE3Y3UycmFYUThLaTJ6dU5uWEkzU1ZrNHh4ZHhkaUE3bE9lR1FuRnVydHpadEJGWTlOWGZzOUdhTDd1eVMyUEhJSzQ2N2RiNjkyVnd1TTdkZkNPM0xmRE03T3dFVW1UNXpKNHZhOEhCc2hTbU9YWU5tT2dQWW1RbjdQWENyMlAybUo4WDY5NUZEZlBsRTBsek1TaEtLaEtteUN3eWl3d0NLVTlpTGx0K296UFk3bmV1ZWFuVE50aXdOV2FaM1c3WmFQY2U1MTlieHZmYlk5dWIySEswQWk5ZS96ejRGNFQ4bXlWc0N2QnhOTUQ2UFpKd1hZcGhkVUJYUUhQaDdRWFh5SXo5eGdwbjRnL2hYdmt1WVdWVFZ1a2lLeGJiY1Bzck45bnFOYzFYd090Y3I0cGl1TnpHZWtwNWZmaS9zMEJtdHpuY1hGVE1TaU9LNzlQLy9rZ2wyM3lWUlNQcGdCMHpycmVmbHBEK2xRK0JDY2tKWTBUOUdjaC9sRVdwMS9pUHQ3Z1FGS2Z4MGpWKzgzSWRKN1ZzcHp3ZlUvZlZKVncxUCtjK3pyRzdnQ1JXS25nUWFzRnlyWFVINFB6V3hUK01QMDZRMU1MWDJsZHVJUkt5RklaaE1ZVTZDTGRXQ2tOT3Nna0lrdTF3dHdvUmhCeisxMXd3bmpGeVVPVEtpTzg5Sm5QbHFyUGZTR0wvYWtPd3Q1SHR2bWRrbXR5aWJwZm12bGVvMXh5TStCLy92ZGs0M0VJS2JFT3lEZUJ1djhHNVpSZDB2eWZUdWkxMWNYK0NqNzhlQUxwQXZMNy9DOU40c2YvQ3dBQS8vOEllaTB1SjBZQUFBPT0=
    csv.yaml: SDRzSUFBQUFBQUFBLzh4WFRZL2JOaEM5KzFjTWNnbFFRTm91MEMvbzFLQU5pZ0ROcHNBR3VSWWphaXhQbHlJWmZpaDJmbjFCU3JaRldzNHVGdW1ITHJzZVBwS1BqNC9ESVJyK1FOYXhWZzFvUXhhOXRxNFcycEtPZjRhYjhSYWwyZUh0NW9GVjE4QXZNamhQOXA3c3lJTG1ycHVCUEhib3Nka0FvRkxhbzJldFhBTXFTTGtCVURoUUE0YjNUTlZ4bG5yOHRyNnRmOXc0UXlMMkU4RjVQVmh5T2xoQkhXMVo4VFRLQmdCQWYxTFVUZjlXTUhINXdKK1piQW9kcHhoVHlOVm1YM2MwemszamNZR250UUIwNUlSbDQxUDgvWTRkc0FOVUp3MWdxeTM4RVFuWEVjM09TRHpjcFRsU0ZON053QTBBSytkUnlvbmNjVG54NjhoSWZSaEllWGNNVlJuUmt4aHphOTQ5ZnBhTVpJR3VnZHRGMUpFazRiVmRJZ0VHOUdMM083WWtYZDRBZ01hVStoY0lvUWVqRlNuL0NPN0w5QUU4RFVhaXA0TGF3aURMVDY2eWZRcmZwek4rblBQMEdZbUtHaEJhZWF0bDFsenVTcUs0VFE0OVhKSlh1cU5YVjF2am5uNE1iS243TlZoVy9iM1lVUmNrcS81TnIvUXAvSHBQSWlSN3Jvd3d6WEUvdStBOTJXRkZRMGgyUzZaNHZUZVduRHVmcGpYa0F4MGFlQWd0V1VXZVhNMzZScnNyYURnZGxBWmU3OW41YThEbkQvdEdYUVdOS0FOZFhVbWNWTElLKzYralNFc2U2MzlJbHVlTy9kVzFpYVpIVm1RdmVsYkFBL2JVUUM5czVEY2ZOZWZtLzR6VjNjMlIyZWx3L1RsMW1qSjhTV0U2am1oTTBlS21TK1dWRURvb2Y3ZHlaMVF6cE1JSlV3emd0WXk0dFUydGdMWmJFcjZCT3oyZk9Mb2d0bUpWdEdKM2dWdHM4c2VBOHFJOTdVRURPSFEvZlBjRkh0TVIvODlwL0d0eTJPRi9JY2VDaGlFN2NKNEZLckJCTGc5UUJXajRONnVEeVV4VndZc1gyVTgweG1VQjI2S29NZmlkdHZ3NXViSisrQ25TejFDMDk2UVNnenpzUlZmSEc3TkZSNHQ2TEFPMU1aTmxFWVgrWWdhakpZdER3WlhQODY2eHl1b25TSGZXVkpjVkdvaXBITFJha3J2VzBMTHFXUFZGdTFaYjdnY3NOTHRhQkdZb1I4S1NkOFVxdTBMQk1kWmRSYitVUGZMZ29rakw0MGlEVnE2Y0oxNjh4Y3l4dkhTZWxCKzFETU1qclVJaUQ0VlJMdFM3S3R1OGdqbjlYVnBtbHIzbzVOSFROc2lMdFFpcjFWKzZ6WU1YZ2VpcDFYR043anAyTnFRcXVnMWRYNDQvVitOcnNadElLbHh1SVlsZzJSK1NaemxUWlNUYkZ1NTcrYzNMeDQrcDg5cGlUMnN1ejA3d0ZZZlAzWVZFNTZnVVppQm5zRFNVY054Wkh2T0ZyN0R2eVdlL0pidHo0Smwzb2ZNV1BmV0habUhyOHd2bGJmUnVKRkdCQzhabzY2bHJ3TnN3SlYxL01OVEF1MC9xN3Jpd1I2RDNySHBKVjlGYmxHNEpmeHVrNTZlTy9Vckt1NlcrRDNUNHBHMDMwMDlTYk9hMG0vN3FOdXFCTFV2Mk1ka055TXVTcGdJYWtHWFVaZng1a2QzVStVbVhPdmxrdndiU1EzRURZS3dldWFQNXBaV2pBWUtWelRsWHhyZGFaTHYrMHYxK3MzaUpUb1hSM3dFQUFQLy9yRldTNVgwUEFBQT0=
  kind: ConfigMap
  metadata:
    annotations:
      olm.contentEncoding: gzip+base64
      olm.sourceImage: gcr.io/pixie-oss/pixie-prod/operator/bundle:0.1.7
      operators.operatorframework.io.bundle.channel.default.v1: stable
      operators.operatorframework.io.bundle.channels.v1: stable,dev
      operators.operatorframework.io.bundle.manifests.v1: manifests/
      operators.operatorframework.io.bundle.mediatype.v1: registry+v1
      operators.operatorframework.io.bundle.metadata.v1: metadata/
      operators.operatorframework.io.bundle.package.v1: pixie-operator
    creationTimestamp: "2025-12-29T09:55:25Z"
    labels:
      olm.managed: "true"
    name: 23864b92b5c58447045dc434f6e35f4f5a3751099701da69e43081a6b7b7a0b
    namespace: px-operator
    ownerReferences:
    - apiVersion: operators.coreos.com/v1alpha1
      blockOwnerDeletion: false
      controller: false
      kind: CatalogSource
      name: pixie-operator-index
      uid: d97438ea-bf9a-4d7d-bb5c-3b9abd2da90a
    resourceVersion: "1729181"
    uid: 7bdc84ac-deab-4d04-9573-9de91b8a2aea
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIE6TCCAtGgAwIBAgIRANjIASdOWLDr5cLe9sHObDAwDQYJKoZIhvcNAQELBQAw
      DTELMAkGA1UEAxMCY2EwIBcNMjUxMjI1MTg1MzA3WhgPMjA1NTEyMjUxOTAzMDda
      MA0xCzAJBgNVBAMTAmNhMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
      zqFJiTcp7nF98f+S2d8DjhNxiu5pca1OZSKnR98sbr62SWJC44ukXV4UJnKODzX9
      WEXZuT7d9VoqJS+ozUTxw+HHWDvFR+6nXZCchAZW7Xwruy/b97WyvX8G2zncbV+D
      5omRmj5MV9k/yrEI1pZKOkXN2e0qosAheLWu7FAFz3rzr0D78kf6Dvy+cyDjS3UF
      wV+gIMb4eb/bU2BwfYSfOdyPbyDNksJBIlD4y+bAwFnj7F2Cf6oZnDCIWkmhCO4Y
      SxIHgQsTISHW/+8TWbVipNU0dcwMBtR0cLDXiVr9xfy2qUd5eVuFIV71S0Dp23U3
      n7qBFgEZj5bhZgfx7B5P79cvien6JWh5XyyDGIH9LNZIRyva4vLjjireW6dpdhlY
      6RnvWBEgbdyfR7DZXWwJTBo+JTShvaRn+fAcyQThs9QkbbB0RCg7oSgCTyeYG0FY
      5nupLcMoMc3hm4+vKiK5Dl0SEhfuP7cCeDZ6uOsNuzwR2P1tO1VTR+6zKpiaBkMh
      tuO7gUkwpGI5wRAJb2OJ6aXBhf6iZyFAZqqXFs3XySWw/HJvw+hHRf+rYilLjMql
      S+ctfsS0QZyKZLhdKpsjXTcMMiOS+3PgGGQnUVvI8eOcCUbQPprpKsnDlefXT4sU
      pQHRJle+6fSp5MH2KoNbNLqkYXZvgfdzsmQrUYaCcD0CAwEAAaNCMEAwDgYDVR0P
      AQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFHPaXTqKELnri6JY
      CK4wZUHjcps2MA0GCSqGSIb3DQEBCwUAA4ICAQAEcabxwprY9W5EskXP/CyG3AfG
      XdknmriAy7HOTqdP8RPvHRKi1BTnhMx7+xWQwVaaU5h+b2fc1ilZJGG2ddlzwxRh
      A1s0wE4D45hrF50gEPEd2ynFr15k9UIV5tTk7WDpOaSFz84SeddyDGGnAnOZhb5f
      ZTGVcYhRLIVmfSPbjrzEcy+IUPa+Fyox13zLCLC+kcK7TO/MOoxlo1bpRfBWtLCM
      RCOsMxFDLwpr+S6zzeW9ZKtS9l+hFhbOH3jcKKvkjpDSwhjaoaWPqheOW/mZu3EM
      iHtfRfwNLtrzn+4MTeDH6gmRzVUO7lOQcs8sIMwrVqUpz/4x2mktX+CbV4zXPGvL
      oa/orqXufuKvNFHc5S5d7tKV0JdSVwJNMKG5LNZJYhVOce/FJaqzKOuH8M/YR+rk
      yuL7H9YKqR17rCIan3zSBhJTIPPxeBrgqZz7j0gagWA1RWRNHUExYXN55sNRxiKU
      29FQLt1ALT6OMHbnbtmMrRH5vrh+WhwE6HT9wfcLUJqJX7s/t4+kol3Oni8QCw1Y
      mAvOjsyttlnzI1eh7Qo4c6tmdaRXn9gN9wOfHkBONYDWYT3eGUeYPXsuP94VSOAI
      MyGcg/9qJDdQBf7rrefI/0doTLCivkyN00+/+6Uw3/Hp04j1wA+7V7xnUTpKCdrv
      y4BESdZ44T2cNIrPmg==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2025-12-29T09:55:04Z"
    name: kube-root-ca.crt
    namespace: px-operator
    resourceVersion: "1728880"
    uid: 33efd4c0-3987-423a-91d6-d229d5fc9a63
- apiVersion: v1
  data:
    nats.conf: |
      pid_file: "/var/run/nats/nats.pid"
      http: 8222

      tls {
        ca_file: "/etc/nats-server-tls-certs/ca.crt",
        cert_file: "/etc/nats-server-tls-certs/server.crt",
        key_file: "/etc/nats-server-tls-certs/server.key",
        timeout: 3
        verify: true
      }
  kind: ConfigMap
  metadata:
    annotations:
      vizier-name: pixie
    creationTimestamp: "2025-12-29T20:15:11Z"
    labels:
      app: pl-monitoring
      vizier-name: pixie
    name: nats-config
    namespace: px-operator
    resourceVersion: "1989893"
    uid: 352545dd-393f-4592-9791-112fb00f4e83
- apiVersion: v1
  data:
    PL_CLOUD_ADDR: withpixie.ai:443
    PL_CLUSTER_NAME: ""
    PL_UPDATE_CLOUD_ADDR: withpixie.ai:443
  kind: ConfigMap
  metadata:
    annotations:
      vizier-name: pixie
    creationTimestamp: "2025-12-29T20:14:57Z"
    labels:
      vizier-name: pixie
    name: pl-cloud-config
    namespace: px-operator
    resourceVersion: "1989786"
    uid: 549b9162-1821-467c-9857-5ad0038931be
- apiVersion: v1
  data:
    PL_CLIENT_TLS_CERT: /certs/client.crt
    PL_CLIENT_TLS_KEY: /certs/client.key
    PL_SERVER_TLS_CERT: /certs/server.crt
    PL_SERVER_TLS_KEY: /certs/server.key
    PL_TLS_CA_CERT: /certs/ca.crt
  kind: ConfigMap
  metadata:
    annotations:
      vizier-name: pixie
    creationTimestamp: "2025-12-29T20:15:12Z"
    labels:
      app: pl-monitoring
      component: vizier
      vizier-bootstrap: "true"
      vizier-name: pixie
    name: pl-cloud-connector-tls-config
    namespace: px-operator
    resourceVersion: "1989934"
    uid: 4a3da109-f480-4888-a752-60dbad105e76
- apiVersion: v1
  data:
    PL_CUSTOM_ANNOTATIONS: ""
    PL_CUSTOM_LABELS: ""
    PL_DISABLE_AUTO_UPDATE: "false"
    PL_ETCD_OPERATOR_ENABLED: "false"
    PL_MD_ETCD_SERVER: https://pl-etcd-client.px-operator.svc:2379
    PX_MEMORY_LIMIT: ""
    PX_MEMORY_REQUEST: ""
  kind: ConfigMap
  metadata:
    annotations:
      vizier-name: pixie
    creationTimestamp: "2025-12-29T20:14:57Z"
    labels:
      vizier-name: pixie
    name: pl-cluster-config
    namespace: px-operator
    resourceVersion: "1989787"
    uid: 60bca4f4-83fa-4a2f-9afd-1a082dee1fb2
- apiVersion: v1
  data:
    PL_CLIENT_TLS_CERT: /certs/client.crt
    PL_CLIENT_TLS_KEY: /certs/client.key
    PL_SERVER_TLS_CERT: /certs/server.crt
    PL_SERVER_TLS_KEY: /certs/server.key
    PL_TLS_CA_CERT: /certs/ca.crt
  kind: ConfigMap
  metadata:
    annotations:
      vizier-name: pixie
    creationTimestamp: "2025-12-29T20:15:12Z"
    labels:
      app: pl-monitoring
      component: vizier
      vizier-name: pixie
    name: pl-tls-config
    namespace: px-operator
    resourceVersion: "1989935"
    uid: 856aa699-46d4-4b55-b3b9-a7b132224e7a
kind: List
metadata:
  resourceVersion: ""
